# Copyright 2023 The OpenVEX Authors
# SPDX-License-Identifier: Apache-2.0

name: ci-build-test

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v2.4.0

      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v2.2.0
        with:
          go-version: '1.20'
          check-latest: true
          cache: true

      - name: build
        run: make vex

  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v2.4.0

      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v2.2.0
        with:
          go-version: '1.20'
          check-latest: true
          cache: true

      - name: test
        run: make test
